prog0: libuser.a prog0.o
	gcc build/objects/prog0.o -o prog0 -luser -Lbuild/lib/

prog0.o:
	gcc src/prog0.c -c -Iinclude
	mkdir -p build/objects/
	mv prog0.o build/objects/

user.o:
	gcc src/user.c -c -Iinclude
	mkdir -p build/objects/
	mv user.o build/objects/

libuser.a: user.o
	ar rs libuser.a build/objects/user.o
	mkdir -p build/lib/
	mv libuser.a build/lib/

clean:
	rm -rf build
	rm prog0